export const DASHBOARD = {
    root: "dashboard-root",
    headerStatsTotal: "stat-total-signals",
    headerStatsHigh: "stat-high-priority",
    headerStatsReg: "stat-total-registrations",
    headerStatsSyllabi: "stat-syllabi-generated",
    addSignalBtn: "add-signal-btn",
    refreshBtn: "refresh-btn",
    signalTable: "signal-tracker-table",
    signalRow: (id) => `signal-row-${id}`,
    signalRowConvert: (id) => `signal-row-convert-${id}`,
    signalRowDelete: (id) => `signal-row-delete-${id}`,
    signalRowPriority: (id) => `signal-row-priority-${id}`,
    // Signal form (create/edit)
    formDialog: "signal-form-dialog",
    formEventTitle: "form-event-title",
    formCategory: "form-category",
    formRegistration: "form-registration-count",
    formPriority: "form-priority-score",
    formSourceUrl: "form-source-url",
    formNotes: "form-notes",
    formSubmit: "form-submit-btn",
    formCancel: "form-cancel-btn",
    // Conversion panel (sheet)
    conversionSheet: "conversion-engine-sheet",
    leadMagnetTitle: "lead-magnet-title-input",
    leadMagnetDesc: "lead-magnet-desc-input",
    paidOfferTitle: "paid-offer-title-input",
    paidOfferDesc: "paid-offer-desc-input",
    paidOfferPrice: "paid-offer-price-input",
    ctaHeadline: "cta-headline-input",
    ctaSubtext: "cta-subtext-input",
    statusSelect: "status-select",
    saveConversion: "save-conversion-btn",
    triggerSyllabus: "trigger-syllabus-btn",
    ctaPreview: "cta-preview-card",
    ctaCopyFreeBtn: "cta-copy-free-btn",
    ctaCopyPaidBtn: "cta-copy-paid-btn",
    syllabusList: "syllabus-modules-list",
};
