export const DASHBOARD = {
    root: "dashboard-root",
    headerStatsTotal: "stat-total-signals",
    headerStatsHigh: "stat-high-priority",
    headerStatsReg: "stat-total-registrations",
    headerStatsSyllabi: "stat-syllabi-generated",
    addSignalBtn: "add-signal-btn",
    refreshBtn: "refresh-btn",
    runScraperBtn: "run-scraper-btn",
    pasteHtmlBtn: "paste-html-btn",
    pasteHtmlDialog: "paste-html-dialog",
    pasteHtmlInput: "paste-html-input",
    pasteHtmlSubmit: "paste-html-submit",
    pasteUrlInput: "paste-url-input",
    pasteUrlSubmit: "paste-url-submit",
    pasteTabHtml: "paste-tab-html",
    pasteTabUrl: "paste-tab-url",
    scraperStatusBar: "scraper-status-bar",
    strikeBanner: "strike-alerts-banner",
    strikeBannerAckAll: "strike-banner-ack-all",
    strikeAlertItem: (id) => `strike-alert-${id}`,
    strikeAlertAck: (id) => `strike-alert-ack-${id}`,
    publishBtn: "publish-to-learnforge-btn",
    publishStatusBadge: "publish-status-badge",
    publishResultPanel: "publish-result-panel",
    republishAllBtn: "republish-all-btn",
    integrationsBadge: "integrations-badge",
    integrationsDialog: "integrations-dialog",
    whatsappTestBtn: "whatsapp-test-btn",
    streamSyllabusBtn: "stream-syllabus-btn",
    velocityChart: "signal-velocity-chart",
    velocityRangeBtn: (label) => `velocity-range-${label.toLowerCase()}`,
    velocityLegendItem: (id) => `velocity-legend-${id}`,
    velocityStrikeDot: (alertId) => `velocity-strike-${alertId}`,
    installBtn: "pwa-install-btn",
    installPrompt: "pwa-install-prompt",
    installDismiss: "pwa-install-dismiss",
    payloadSpecBtn: "payload-spec-btn",
    payloadSpecDialog: "payload-spec-dialog",
    handoffCopyBtn: "learnforge-handoff-copy-btn",
    handoffDownloadBtn: "learnforge-handoff-download-btn",
    handoffCallout: "learnforge-handoff-callout",
    webhookSpecBtn: "webhook-spec-btn",
    webhookSpecDialog: "webhook-spec-dialog",
    webhookSpecCopyBtn: "webhook-spec-copy-btn",
    libraryPatchBtn: "library-patch-btn",
    libraryPatchDialog: "library-patch-dialog",
    libraryPatchCopyBtn: "library-patch-copy-btn",
    heroPatchBtn: "hero-patch-btn",
    heroPatchDialog: "hero-patch-dialog",
    heroPatchCopyBtn: "hero-patch-copy-btn",
    signalTable: "signal-tracker-table",
    signalRow: (id) => `signal-row-${id}`,
    signalRowConvert: (id) => `signal-row-convert-${id}`,
    signalRowDelete: (id) => `signal-row-delete-${id}`,
    signalRowPriority: (id) => `signal-row-priority-${id}`,
    // Signal form (create/edit)
    formDialog: "signal-form-dialog",
    formEventTitle: "form-event-title",
    formCategory: "form-category",
    formRegistration: "form-registration-count",
    formPriority: "form-priority-score",
    formSourceUrl: "form-source-url",
    formNotes: "form-notes",
    formSubmit: "form-submit-btn",
    formCancel: "form-cancel-btn",
    // Conversion panel (sheet)
    conversionSheet: "conversion-engine-sheet",
    leadMagnetTitle: "lead-magnet-title-input",
    leadMagnetDesc: "lead-magnet-desc-input",
    paidOfferTitle: "paid-offer-title-input",
    paidOfferDesc: "paid-offer-desc-input",
    paidOfferPrice: "paid-offer-price-input",
    ctaHeadline: "cta-headline-input",
    ctaSubtext: "cta-subtext-input",
    statusSelect: "status-select",
    saveConversion: "save-conversion-btn",
    triggerSyllabus: "trigger-syllabus-btn",
    ctaPreview: "cta-preview-card",
    ctaCopyFreeBtn: "cta-copy-free-btn",
    ctaCopyPaidBtn: "cta-copy-paid-btn",
    syllabusList: "syllabus-modules-list",
    publishErrorBtn: (id) => `publish-error-btn-${id}`,
    publishErrorDialog: "publish-error-dialog",
    syncDriftBadge: "sync-drift-badge",
    // CourseBriefV2 dispatch (v2)
    briefPreviewBtn: "brief-preview-btn",
    briefPreviewJson: "brief-preview-json",
    dispatchBriefBtn: "dispatch-brief-btn",
    dispatchResultPanel: "dispatch-result-panel",
    jobStatusChip: "job-status-chip",
    jobRefreshBtn: "job-refresh-btn",
    jobPublicUrl: "job-public-url",
};
