// LearnForge — app/[locale]/library/page.tsx (DROP-IN PATCH)
//
// Fixes the "Radar Curriculums visible to non-purchasers" security leak.
//
// Save this file at: learnforge-core/app/[locale]/library/page.tsx
//
// Generated by LearnForge Opportunity Radar. Adjust table/column names to
// match your Supabase schema where indicated by "// ADJUST:" comments.

import { redirect } from "next/navigation";
import Link from "next/link";
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";

// =====================================================================
// 1) Supabase client (server-side, cookie-aware)
// =====================================================================
function supabaseServer() {
    const cookieStore = cookies();
    return createServerClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        {
            cookies: {
                get: (name: string) => cookieStore.get(name)?.value,
                set: () => {},
                remove: () => {},
            },
        },
    );
}

// =====================================================================
// 2) Auth + admin check
//    ADJUST: change ADMIN_EMAILS to match your architect emails, or move
//            this to a `profiles.is_admin` boolean column.
// =====================================================================
const ADMIN_EMAILS = (process.env.LEARNFORGE_ADMIN_EMAILS ?? "")
    .split(",")
    .map((e) => e.trim().toLowerCase())
    .filter(Boolean);

function isAdmin(email: string | null | undefined): boolean {
    if (!email) return false;
    return ADMIN_EMAILS.includes(email.toLowerCase());
}

// =====================================================================
// 3) Server-side data fetch — the security boundary
// =====================================================================
type CourseRow = {
    id: string;
    slug: string;
    title: string;
    category: string | null;
    summary: string | null;
    hero_image_url: string | null;
    price_usd: number | null;
    original_price_usd: number | null;
    discount_pct: number | null;
    source: string | null; // "radar" | "manual" etc.
};

async function loadAccessibleCourses(): Promise<{
    courses: CourseRow[];
    userEmail: string | null;
    admin: boolean;
}> {
    const supabase = supabaseServer();
    const {
        data: { user },
    } = await supabase.auth.getUser();

    if (!user) return { courses: [], userEmail: null, admin: false };
    const admin = isAdmin(user.email);

    // ADMIN PATH — see everything, regardless of purchase.
    if (admin) {
        const { data: rows } = await supabase
            .from("courses")
            .select(
                "id, slug, title, category, summary, hero_image_url, price_usd, original_price_usd, discount_pct, source",
            )
            .order("created_at", { ascending: false });
        return { courses: (rows ?? []) as CourseRow[], userEmail: user.email!, admin };
    }

    // STUDENT PATH — only courses the user actually has access to.
    // ADJUST: change `user_purchases` to your real table name and join key.
    const { data: purchases } = await supabase
        .from("user_purchases")
        .select("course_id")
        .eq("user_id", user.id)
        .eq("status", "active"); // or .in("status", ["active","trial"])

    const courseIds = (purchases ?? []).map((p) => p.course_id);
    if (courseIds.length === 0) {
        return { courses: [], userEmail: user.email!, admin };
    }

    const { data: rows } = await supabase
        .from("courses")
        .select(
            "id, slug, title, category, summary, hero_image_url, price_usd, original_price_usd, discount_pct, source",
        )
        .in("id", courseIds)
        .order("created_at", { ascending: false });

    return { courses: (rows ?? []) as CourseRow[], userEmail: user.email!, admin };
}

// =====================================================================
// 4) UI helpers
// =====================================================================
function discountBadge(course: CourseRow) {
    // Read pre-computed discount from the payload (Radar already rounded it).
    const pct = course.discount_pct;
    if (pct == null || pct <= 0) return null;
    return (
        <span className="inline-flex items-center rounded-sm border border-lime-400/60 bg-lime-400/10 text-lime-300 font-mono text-[10px] uppercase tracking-[0.2em] font-bold px-2 py-0.5">
            {pct}% OFF
        </span>
    );
}

function CourseCard({ course }: { course: CourseRow }) {
    return (
        <Link
            href={`/courses/${course.slug}`}
            className="group border border-zinc-800 rounded-sm overflow-hidden hover:border-lime-400/60 transition-colors"
        >
            {course.hero_image_url && (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                    src={course.hero_image_url}
                    alt={course.title}
                    loading="lazy"
                    className="w-full aspect-[16/9] object-cover"
                />
            )}
            <div className="p-4">
                <div className="flex items-center gap-2 mb-2">
                    {course.source === "radar" && (
                        <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-lime-400">
                            Radar Curriculum
                        </span>
                    )}
                    {discountBadge(course)}
                </div>
                <h3 className="font-mono text-base font-bold text-zinc-50 group-hover:text-lime-300">
                    {course.title}
                </h3>
                {course.summary && (
                    <p className="mt-1 text-xs text-zinc-400 line-clamp-2">
                        {course.summary}
                    </p>
                )}
            </div>
        </Link>
    );
}

// =====================================================================
// 5) Page (server component)
// =====================================================================
export default async function LibraryPage({
    params,
}: {
    params: { locale: string };
}) {
    const { courses, userEmail, admin } = await loadAccessibleCourses();

    if (userEmail === null) {
        // Not signed in. Push them to the public showroom + auth.
        redirect(`/${params.locale}/signup?next=/library`);
    }

    return (
        <div className="min-h-screen bg-zinc-950 text-zinc-50">
            <header className="border-b border-zinc-800 px-6 py-8">
                <h1 className="font-mono text-3xl font-bold tracking-tight">
                    My Library
                    {admin && (
                        <span className="ml-3 inline-flex items-center rounded-sm border border-lime-400/60 bg-lime-400/10 text-lime-300 font-mono text-[10px] uppercase tracking-[0.2em] px-2 py-0.5 align-middle">
                            Architect · sees all
                        </span>
                    )}
                </h1>
                <p className="mt-1 text-sm text-zinc-400">
                    {admin
                        ? "Admin view — every course in the catalog."
                        : "Courses you've purchased or been granted access to."}
                </p>
            </header>

            <main className="px-6 py-8">
                {courses.length === 0 ? (
                    <EmptyState locale={params.locale} />
                ) : (
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                        {courses.map((c) => (
                            <CourseCard key={c.id} course={c} />
                        ))}
                    </div>
                )}
            </main>
        </div>
    );
}

function EmptyState({ locale }: { locale: string }) {
    return (
        <div className="border border-dashed border-zinc-800 rounded-sm p-12 text-center max-w-2xl mx-auto">
            <h2 className="font-mono text-xl font-bold text-zinc-100">
                Your library is empty.
            </h2>
            <p className="mt-2 text-sm text-zinc-400 max-w-md mx-auto">
                Premium Radar Curriculums are forged from live demand
                signals. Explore what's currently outperforming the market.
            </p>
            <Link
                href={`/${locale}/showroom`}
                className="inline-flex items-center gap-2 mt-6 bg-lime-400 hover:bg-lime-300 text-black font-mono text-xs uppercase tracking-[0.2em] font-bold px-4 py-2.5 rounded-sm transition-colors"
            >
                Explore Premium Outcomes
                <span aria-hidden>→</span>
            </Link>
        </div>
    );
}

// =====================================================================
// 6) Minimum SQL — run on Supabase if these don't already exist
// =====================================================================
/*
-- user_purchases: which user owns which course
CREATE TABLE IF NOT EXISTS public.user_purchases (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id     uuid NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
    status        text NOT NULL DEFAULT 'active',  -- active | trial | refunded
    granted_at    timestamptz NOT NULL DEFAULT now(),
    expires_at    timestamptz NULL,
    source        text NULL,                       -- "stripe" | "manual_grant" | "promo"
    UNIQUE (user_id, course_id)
);

-- RLS: a user can only read their own purchase rows. Admins use service-role
-- which bypasses RLS automatically.
ALTER TABLE public.user_purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_reads_own_purchases"
    ON public.user_purchases FOR SELECT
    USING (auth.uid() = user_id);

-- courses: read access is per-row driven by user_purchases for non-admins.
-- (If you'd rather keep the courses table publicly readable and gate ONLY
--  the library page, leave courses as-is — the server-side `.in("id",...)`
--  filter above is the actual security boundary for the library route.)
*/
