// LearnForge — POST /api/courses webhook receiver (Next.js 14 App Router)
//
// DROP-IN: Save as `app/api/courses/route.ts` in learnforge-core.
//
// Once deployed, the Radar's "Publish to LearnForge" flow will flip from
// HTTP 404 → HTTP 200 automatically — no Radar-side changes required.
// Set LEARNFORGE_WEBHOOK_SECRET in Vercel env to enable signature verification.
//
// Auto-generated by LearnForge Opportunity Radar — keep this file in sync
// with the Radar's JSON-Schema published at:
//   GET https://<radar-host>/api/integrations/publish-payload-spec

import { NextRequest, NextResponse } from "next/server";
import crypto from "node:crypto";
import { z } from "zod";

// ---------------------------------------------------------------------------
// 1) Payload contract — kept in lockstep with Radar's `course.publish` spec.
// ---------------------------------------------------------------------------
const Module = z.object({
    index: z.number().int().min(1),
    title: z.string(),
    summary: z.string(),
    learning_objectives: z.array(z.string()).optional().default([]),
    artifact: z.string().optional().default(""),
    duration_min: z.number().int(),
});

const CoursePublish = z.object({
    event: z.literal("course.publish"),
    signal_id: z.string().uuid(),
    published_at: z.string(),
    course: z.object({
        slug: z.string().min(1),
        title: z.string().min(1),
        category: z.string(),
        summary: z.string().optional().default(""),
        price_usd: z.number().nullable().optional(),
        lead_magnet: z
            .object({
                title: z.string().optional().default(""),
                description: z.string().optional().default(""),
                slug: z.string().nullable().optional(),
                url: z.string().url().nullable().optional(),
            })
            .optional()
            .default({ title: "", description: "" }),
        cta: z.object({
            headline: z.string().optional().default(""),
            subtext: z.string().optional().default(""),
            free_url: z.string().url().nullable().optional(),
            paid_url: z.string().url(),
        }),
        syllabus: z.object({ modules: z.array(Module) }),
        demand: z.object({
            registration_count: z.number().int(),
            priority_score: z.number().int().min(0).max(100),
            source_url: z.string().url().nullable().optional(),
        }),
    }),
});

type CoursePublishPayload = z.infer<typeof CoursePublish>;

// ---------------------------------------------------------------------------
// 2) Signature verification — HMAC-SHA256 of the raw request body using the
//    shared secret. Header format: `sha256=<64-char hex>`.
//    Constant-time compare via crypto.timingSafeEqual.
// ---------------------------------------------------------------------------
function verifySignature(rawBody: string, header: string | null): boolean {
    const secret = process.env.LEARNFORGE_WEBHOOK_SECRET;
    if (!secret) return true; // signing disabled — accept all
    if (!header) return false;

    const provided = header.startsWith("sha256=") ? header.slice(7) : header;
    const expected = crypto
        .createHmac("sha256", secret)
        .update(rawBody)
        .digest("hex");

    if (provided.length !== expected.length) return false;
    try {
        return crypto.timingSafeEqual(
            Buffer.from(provided, "hex"),
            Buffer.from(expected, "hex"),
        );
    } catch {
        return false;
    }
}

// ---------------------------------------------------------------------------
// 3) Upsert — replace this stub with your DB layer of choice.
//    Idempotent on `course.slug`; Radar may re-fire the same payload on retry.
// ---------------------------------------------------------------------------
async function upsertCourse(payload: CoursePublishPayload) {
    const { signal_id, course } = payload;

    // === PRISMA example (uncomment + adapt) ================================
    // return prisma.course.upsert({
    //     where: { slug: course.slug },
    //     update: {
    //         signalId: signal_id,
    //         title: course.title,
    //         category: course.category,
    //         summary: course.summary,
    //         priceUsd: course.price_usd ?? null,
    //         ctaHeadline: course.cta.headline,
    //         ctaSubtext: course.cta.subtext,
    //         freeUrl: course.cta.free_url,
    //         paidUrl: course.cta.paid_url,
    //         leadMagnetTitle: course.lead_magnet?.title ?? "",
    //         leadMagnetDescription: course.lead_magnet?.description ?? "",
    //         leadMagnetSlug: course.lead_magnet?.slug ?? null,
    //         registrationCount: course.demand.registration_count,
    //         priorityScore: course.demand.priority_score,
    //         sourceUrl: course.demand.source_url,
    //         modules: {
    //             deleteMany: {},
    //             create: course.syllabus.modules.map((m) => ({
    //                 index: m.index,
    //                 title: m.title,
    //                 summary: m.summary,
    //                 learningObjectives: m.learning_objectives,
    //                 artifact: m.artifact,
    //                 durationMin: m.duration_min,
    //             })),
    //         },
    //     },
    //     create: {
    //         slug: course.slug,
    //         signalId: signal_id,
    //         title: course.title,
    //         category: course.category,
    //         summary: course.summary,
    //         priceUsd: course.price_usd ?? null,
    //         ctaHeadline: course.cta.headline,
    //         ctaSubtext: course.cta.subtext,
    //         freeUrl: course.cta.free_url,
    //         paidUrl: course.cta.paid_url,
    //         leadMagnetTitle: course.lead_magnet?.title ?? "",
    //         leadMagnetDescription: course.lead_magnet?.description ?? "",
    //         leadMagnetSlug: course.lead_magnet?.slug ?? null,
    //         registrationCount: course.demand.registration_count,
    //         priorityScore: course.demand.priority_score,
    //         sourceUrl: course.demand.source_url,
    //         modules: {
    //             create: course.syllabus.modules.map((m) => ({
    //                 index: m.index,
    //                 title: m.title,
    //                 summary: m.summary,
    //                 learningObjectives: m.learning_objectives,
    //                 artifact: m.artifact,
    //                 durationMin: m.duration_min,
    //             })),
    //         },
    //     },
    // });

    // === DEFAULT stub — logs only so the route returns 200 immediately. =====
    console.log("[radar] course.publish", {
        signal_id,
        slug: course.slug,
        title: course.title,
        modules: course.syllabus.modules.length,
        registrations: course.demand.registration_count,
        priority: course.demand.priority_score,
    });
    return { id: `lf_${course.slug}`, slug: course.slug };
}

// ---------------------------------------------------------------------------
// 4) Route handler.
// ---------------------------------------------------------------------------
export async function POST(req: NextRequest) {
    // Read raw body first — HMAC must be computed over the byte-identical
    // payload the Radar signed. Don't call req.json() before this.
    const rawBody = await req.text();

    if (!verifySignature(rawBody, req.headers.get("x-radar-signature"))) {
        return NextResponse.json(
            { ok: false, error: "bad signature" },
            { status: 401 },
        );
    }

    let body: unknown;
    try {
        body = JSON.parse(rawBody);
    } catch {
        return NextResponse.json(
            { ok: false, error: "invalid json" },
            { status: 400 },
        );
    }

    const parsed = CoursePublish.safeParse(body);
    if (!parsed.success) {
        return NextResponse.json(
            {
                ok: false,
                error: "invalid payload",
                issues: parsed.error.issues,
            },
            { status: 422 },
        );
    }

    try {
        const courseRow = await upsertCourse(parsed.data);
        return NextResponse.json(
            {
                ok: true,
                course_id: courseRow.id,
                slug: courseRow.slug,
                signal_id: parsed.data.signal_id,
            },
            { status: 200 },
        );
    } catch (err) {
        const msg = err instanceof Error ? err.message : "unknown error";
        console.error("[radar] upsert failed:", msg);
        return NextResponse.json(
            { ok: false, error: "upsert failed", detail: msg },
            { status: 500 },
        );
    }
}

// Health-check ping so a GET to the same URL returns 200 (useful for
// uptime monitors). Radar only ever POSTs.
export async function GET() {
    return NextResponse.json({
        ok: true,
        service: "learnforge-course-publish",
        version: "v1",
    });
}

export const runtime = "nodejs"; // crypto.timingSafeEqual requires Node runtime
export const dynamic = "force-dynamic"; // never cache mutations
